### ISSUE TITLE
Webhook failed due to HTTPServiceUnavailable

### ISSUE THREAD

**Issue by msoha** [EugenMayer/docker-image-portus#6]
I’m not able to get information about pushed images synchronized and visible in Portus UI.

Image push is performed successfully but I’m getting exception after push webhook is received: 
portus      | Exception: Cannot obtain authorization token: #Net::HTTPServiceUnavailable:0x007ff87e164738>

Same error is produced on Perform CatalogJob.

Changes that I made to your referential setup are:
- Paswords in docker-compose
- Fullchain and privkey certificates
- Hostnames in docker-compose as well as in nginx conf files
- Original registry tag 2.5.0 switched to 2.3.1

Composition starting by test_start.sh
I'm quite new to this, so any advice where to look for root cause is appreciated.

**Comment by EugenMayer** [comment]
Did you use the image as part of my rancher catalog or did you configure a own stack?

**Comment by msoha** [comment]
I haven't used rancher catalog.

**Comment by EugenMayer** [comment]
Please post your docker-compose.yml file

**Comment by EugenMayer** [comment]
You might get a better insight by looking at the rancher definition: 

https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/registry-slim/17/docker-compose.yml and the corresponding questions https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/registry-slim/17/rancher-compose.yml

That should give you an good idea how you need to setup both, the registry and portus so the comms work properly

**Comment by msoha** [comment]
Some entries have been anonymized, but the structure remained the same.
```
version: '2'
services:
  db:
    container_name: portus_db
    image: percona:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "somepassword"
  portus:
    image: eugenmayer/portus:2.4-rc8
    container_name: portus
    build:
      context: .
    environment:
      PORTUS_DEBUG: 'true'
      #PORTUS_CREATE_CERT: 'false'
      PORTUS_ADMIN_PASSWORD: 'adminpass'
      REGISTRY_SSL_ENABLED: 'true'
      REGISTRY_HOSTNAME: registry.company.com
      REGISTRY_PORT: 443
      REGISTRY_NAME: Registry
      PORTUS_MACHINE_FQDN: portus.company.com
      PORTUS_PORT: 443
      PORTUS_PRODUCTION_HOST: db
      PORTUS_PRODUCTION_DATABASE: portus
      PORTUS_PRODUCTION_USERNAME: root
      PORTUS_PRODUCTION_PASSWORD: "somepassword"
      PORTUS_DEVELOPMENT_HOST: db
      PORTUS_DEVELOPMENT_DATABASE: portus
      PORTUS_DEVELOPMENT_USERNAME: root
      PORTUS_DEVELOPMENT_PASSWORD: "somepassword"
      PORTUS_GRAVATAR_ENABLED: 'true'
      PORTUS_DELETE_ENABLED: 'true'
      PORTUS_KEY_PATH: /certs/privkey.pem
      PORTUS_CRT_PATH: /certs/fullchain.pem
      PORTUS_PASSWORD: "somepassword"
      PORTUS_SECRET_KEY_BASE: something
      PORTUS_CHECK_SSL_USAGE_ENABLED: 'true'
      PORTUS_SMTP_ENABLED: 'false'
      PORTUS_SMTP_ADDRESS: 'smtp.example.com'
      PORTUS_SMTP_PORT: 587
      PORTUS_SMTP_USER_NAME: 'username@example.com'
      PORTUS_SMTP_PASSWORD: 'password'
      PORTUS_SMTP_DOMAIN: 'example.com'
      PORTUS_LDAP_ENABLED: 'false'
      PORTUS_LDAP_HOSTNAME: ""
      PORTUS_LDAP_PORT: ""
      PORTUS_LDAP_METHOD: ""
      PORTUS_LDAP_BASE: ""
      PORTUS_LDAP_UID: cn
      PORTUS_LDAP_AUTHENTICATION_ENABLED: ""
      PORTUS_LDAP_AUTHENTICATION_BIND_DN: ""
      PORTUS_LDAP_AUTHENTICATION_PASSWORD: ""
      PORTUS_LDAP_GUESS_EMAIL_ENABLED: 'true'
      PORTUS_LDAP_GUESS_EMAIL_ATTR: mail
      PORTUS_REGISTRY_JWT_EXIRATION_TIME: 30
      RAILS_ENV: 'production'
    volumes:
      - ./certs:/certs
    depends_on:
      - db
      - registry
    external_links:
      - "nginx:registry.company.com"
  registry:
    image: registry:2.3.1
    container_name: registry
    environment:
      REGISTRY_LOG_LEVEL: warn
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: https://portus.company.com:443/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: registry.company.com:443
      REGISTRY_AUTH_TOKEN_ISSUER: portus.company.com
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/fullchain.pem
      REGISTRY_HTTP_SECRET: somethingother
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://portus.company.com/v2/webhooks/events
          timeout: 5000
          threshold: 5
          backoff: 20s

    volumes:
      - ./certs:/certs
      - /var/local/docker_registry_data:/var/lib/registry
    external_links:
      - "nginx:portus.company.com"
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./proxy/portus.company.com.conf:/etc/nginx/conf.d/portus.company.com.conf:ro
      - ./proxy/registry.company.com.conf:/etc/nginx/conf.d/registry.company.com.conf:ro
      - ./certs:/certs
    depends_on:
      - portus
      - registry
    ports:
      - "443:443"
    external_links:
      - "portus:portus.company.com"
      - "registry:registry.company.com"
```
